### PR TITLE
Use correct keys for measurement & label

### LINKED ISSUE #9: Measurement parsing fails
After measurement stop I get an error:

```
react-perf-tool.js:4351 Uncaught TypeError: Cannot read property 'split' of undefined
```

On this line:

```
var label = measurement['Owner > component'].split(' > ').pop();
```

### PR DESCRIPTION
**Pull request by jfsiii**
Fixes #9 

The code expects a different data structure than what React 15.1.0 provides. Here's an example of objects logged to the console.

```
[
 {
   "key": "LazyList > ScribeNamespaceContainer",
   "instanceCount": 15,
   "inclusiveRenderDuration": 4.610000000007858,
   "renderCount": 40
 },
 {
   "key": "ScribeNamespaceContainer > ScribeProvider",
   "instanceCount": 15,
   "inclusiveRenderDuration": 2.085000000000946,
   "renderCount": 40
 },
 {
   "key": "ScribeNamespaceContainer > ScribePropsContainer",
   "instanceCount": 15,
   "inclusiveRenderDuration": 1.9400000000023283,
   "renderCount": 40
 },
 {
   "key": "LazyList > Waypoint",
   "instanceCount": 1,
   "inclusiveRenderDuration": 0.04499999999825377,
   "renderCount": 3
 }
]
```

### CODE REVIEW

File: src/components/ChartComponent.js [hunk 1]
```diff
@@ -19,8 +19,8 @@ class ChartComponent extends Component {
   }
 
   renderChart(measurements) {
-    const data = measurements.map(measurement => measurement['Wasted time (ms)']);
-    const labels = measurements.map(measurement => measurement['Owner > component']);
+    const data = measurements.map(measurement => measurement.inclusiveRenderDuration);
+    const labels = measurements.map(measurement => measuremen.key);
```
Comment (RamonGebben) [inline src/components/ChartComponent.js]: @jfsiii I think you made a typo here. Could you resolve this.
Once tests pass I will merge :)
